project_name: argo-apps-viz
release:
  github:
    owner: syndlex
    name: argo-apps-viz
builds:
  - id: argo-apps-viz
    main: cmd/plugin/main.go
    binary: argo-apps-viz
    env:
      - CGO_ENABLED=0
    goos:
    - linux
    - darwin
    - windows
    goarch:
    - amd64
    - arm64
archives:
  - id: argo-apps-viz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    builds:
    - argo-apps-viz
    format_overrides:
    - goos: windows
      format: zip
    files: ["LICENSE"]
checksum:
  name_template: "checksums.txt"
  algorithm: sha256