project_name: argo-apps-viz
release:
  github:
    owner: syndlex
    name: argo-apps-viz
builds:
  - id: argo-apps-viz
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/plugin/main.go
    ldflags: -s -w
      -X github.com/syndlex/argo-apps-viz/pkg/version.version={{.Version}}
    flags: -tags netgo -installsuffix netgo
    binary: argo-apps-viz
archives:
  - id: argo-apps-viz
    format: tar.gz
    builds:
    - argo-apps-viz
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*
      - changelog*
      - CHANGELOG*