project_name: argo-apps-viz
release:
  github:
    owner: syndlex
    name: argo-apps-viz
builds:
  - id: argo-apps-viz
    main: cmd/plugin/main.go
    binary: argo-apps-viz
    env:
      - CGO_ENABLED=0
    goos:
    - linux
    - darwin
    - windows
    goarch:
    - amd64
    - arm
    - arm64
    - ppc64le
    - s390x
    goarm: [6, 7]
archives:
  - id: argo-apps-viz
    name_template: |-
      argo-apps-viz_{{ .Tag }}_{{ .Os }}_
      {{- with .Arch -}}
        {{- if (eq . "386") -}}i386
        {{- else if (eq . "amd64") -}}x86_64
        {{- else -}}{{- . -}}
        {{- end -}} 
      {{ end }}
      {{- with .Arm -}}
        {{- if (eq . "6") -}}hf
        {{- else -}}v{{- . -}}
        {{- end -}}
      {{- end -}}
    builds:
    - argo-apps-viz
    format_overrides:
    - goos: windows
      format: zip
    files: ["LICENSE"]
checksum:
  name_template: "checksums.txt"
  algorithm: sha256